### ISSUE TITLE
build web error

### ISSUE THREAD

**Issue by navidonline** [SongbookPro/flutter_windows_single_instance#1]
/I:/SDK/Flutter/.pub-cache/hosted/pub.dartlang.org/win32-2.6.1/lib/src/structs.g.dart:8145:16:
Error: Only JS interop members may be 'external'.
  external int tv_usec;
               ^
/I:/SDK/Flutter/.pub-cache/hosted/pub.dartlang.org/win32-2.6.1/lib/src/combase.dart:24:37:
Error: Only JS interop members may be 'external'.
  external Pointer<Pointer<IntPtr>> lpVtbl;
                                    ^
Error: Compilation failed.

**Comment by Jon-Salmon** [comment]
Resolved in 0.1.3 (57e8e098cc0ff9440f892ebaedd5dcb579f7312c)
