### ISSUE TITLE
Wrong Single Instance Detection

### ISSUE THREAD

**Issue by happy-mammal** [SongbookPro/flutter_windows_single_instance#2]
I have  a following scenario, where I have 2 apps which are dependent on each other and run together during there entire lifecycle.

[APP 1] One is the client app with whom the users interact and see it. 

[APP 2] Is  kind of service app and it is not visible to users it just runs in background but is built with flutter and has only main method and does not executes runApp(). So basically no GUI as well. For example this is what my main method looks for this app.

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await WindowsSingleInstance.ensureSingleInstance(
    [],
    "saapakts",
    onSecondWindow: (args) {},
  );

  //SOME LOGIC CODE WITH A TIMER 
}

Now the thing is i have used your package in both the apps since i want to ensure both of them have single instance also i have passed different identifiers as well to distinguish. It works perfect as well but only when one app is run.

Like if i run [APP1] or [APP2] and try to launch another instance of that particular app in that case the package works as intended.

But if i run [APP1] and try to launch [APP2] both being single instance it prevents another one from running. Like if i have opened [APP1] it does not allows [APP2] to run and vice versa.

It seems to be a impacting issue and its currently impacting my development. Please look into this.

**Comment by Jon-Salmon** [comment]
Resolved in 0.1.3 (90b1c93d95ee1bc1d9e583334a0f15ea013a31bb)
