### ISSUE TITLE
Support for win32 5.x.x

### ISSUE THREAD

**Issue by aweinber** [SongbookPro/flutter_windows_single_instance#9]
Hi,

I'd like to use a struct introduced in win32 5.0.7. I can create a pull request to bump the versions - any concerns there?

Thanks

**Comment by Jon-Salmon** [comment]
Please feel free to

**Comment by Jon-Salmon** [comment]
Resolved in #10

**Comment by aweinber** [comment]
Ah just saw - thank you @aexei
